from PyQt6 import QtCore, QtWidgets


class Ui_TavlaGameWindow(object):
    def setupUi(self, TavlaGameWindow):
        TavlaGameWindow.setObjectName("TavlaGameWindow")
        TavlaGameWindow.setWindowTitle("Online Tavla - Python PyQt6")
        TavlaGameWindow.resize(1280, 620)
        TavlaGameWindow.setMinimumSize(1100, 560)

        self.rootLayout = QtWidgets.QVBoxLayout(TavlaGameWindow)
        self.rootLayout.setContentsMargins(10, 10, 10, 10)
        self.rootLayout.setSpacing(10)

        self.controls = QtWidgets.QFrame(parent=TavlaGameWindow)
        self.controls.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.controlsLayout = QtWidgets.QHBoxLayout(self.controls)
        self.controlsLayout.setContentsMargins(10, 8, 10, 8)
        self.controlsLayout.setSpacing(12)

        self.btn_roll = QtWidgets.QPushButton(parent=self.controls)
        self.btn_roll.setText("🎲 Zar At")
        self.btn_roll.setMinimumSize(110, 34)
        self.controlsLayout.addWidget(self.btn_roll)

        self.lbl_dice = QtWidgets.QLabel(parent=self.controls)
        self.lbl_dice.setText("Zar Sonucu")
        self.lbl_dice.setStyleSheet("font-weight: bold; font-size: 14px;")
        self.controlsLayout.addWidget(self.lbl_dice)

        self.lbl_current_player = QtWidgets.QLabel(parent=self.controls)
        self.lbl_current_player.setText("Oyuncu Sırası")
        self.lbl_current_player.setStyleSheet("font-weight: bold; font-size: 14px;")
        self.controlsLayout.addWidget(self.lbl_current_player)
        self.controlsLayout.addStretch()

        self.btn_leave = QtWidgets.QPushButton(parent=self.controls)
        self.btn_leave.setText("Ana Menü")
        self.btn_leave.setMinimumSize(90, 34)
        self.controlsLayout.addWidget(self.btn_leave)
        self.rootLayout.addWidget(self.controls)

        self.role_bar = QtWidgets.QFrame(parent=TavlaGameWindow)
        self.roleLayout = QtWidgets.QHBoxLayout(self.role_bar)
        self.roleLayout.setContentsMargins(10, 6, 10, 6)
        self.lbl_role_badge = QtWidgets.QLabel(parent=self.role_bar)
        self.lbl_role_badge.setStyleSheet("font-size: 15px; font-weight: bold;")
        self.roleLayout.addWidget(self.lbl_role_badge)
        self.roleLayout.addStretch()
        self.rootLayout.addWidget(self.role_bar)

        self.bodyLayout = QtWidgets.QHBoxLayout()
        self.bodyLayout.setSpacing(12)
        self.rootLayout.addLayout(self.bodyLayout, 1)

        self.board_frame = QtWidgets.QFrame(parent=TavlaGameWindow)
        self.board_layout = QtWidgets.QGridLayout(self.board_frame)
        self.board_layout.setContentsMargins(0, 0, 0, 0)
        self.board_layout.setHorizontalSpacing(6)
        self.board_layout.setVerticalSpacing(8)
        self.bodyLayout.addWidget(self.board_frame, 1)

        self.top_left = QtWidgets.QFrame(parent=self.board_frame)
        self.top_right = QtWidgets.QFrame(parent=self.board_frame)
        self.bottom_left = QtWidgets.QFrame(parent=self.board_frame)
        self.bottom_right = QtWidgets.QFrame(parent=self.board_frame)
        self.top_left_layout = QtWidgets.QHBoxLayout(self.top_left)
        self.top_right_layout = QtWidgets.QHBoxLayout(self.top_right)
        self.bottom_left_layout = QtWidgets.QHBoxLayout(self.bottom_left)
        self.bottom_right_layout = QtWidgets.QHBoxLayout(self.bottom_right)
        for layout in (self.top_left_layout, self.top_right_layout, self.bottom_left_layout, self.bottom_right_layout):
            layout.setContentsMargins(0, 0, 0, 0)
            layout.setSpacing(5)

        self.btn13 = QtWidgets.QPushButton(parent=self.top_left)
        self.btn13.setText("13")
        self.btn13.setMinimumSize(76, 140)
        self.btn13.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.top_left_layout.addWidget(self.btn13, 1)

        self.btn14 = QtWidgets.QPushButton(parent=self.top_left)
        self.btn14.setText("14")
        self.btn14.setMinimumSize(76, 140)
        self.btn14.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.top_left_layout.addWidget(self.btn14, 1)

        self.btn15 = QtWidgets.QPushButton(parent=self.top_left)
        self.btn15.setText("15")
        self.btn15.setMinimumSize(76, 140)
        self.btn15.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.top_left_layout.addWidget(self.btn15, 1)

        self.btn16 = QtWidgets.QPushButton(parent=self.top_left)
        self.btn16.setText("16")
        self.btn16.setMinimumSize(76, 140)
        self.btn16.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.top_left_layout.addWidget(self.btn16, 1)

        self.btn17 = QtWidgets.QPushButton(parent=self.top_left)
        self.btn17.setText("17")
        self.btn17.setMinimumSize(76, 140)
        self.btn17.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.top_left_layout.addWidget(self.btn17, 1)

        self.btn18 = QtWidgets.QPushButton(parent=self.top_left)
        self.btn18.setText("18")
        self.btn18.setMinimumSize(76, 140)
        self.btn18.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.top_left_layout.addWidget(self.btn18, 1)

        self.btn19 = QtWidgets.QPushButton(parent=self.top_right)
        self.btn19.setText("19")
        self.btn19.setMinimumSize(76, 140)
        self.btn19.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.top_right_layout.addWidget(self.btn19, 1)

        self.btn20 = QtWidgets.QPushButton(parent=self.top_right)
        self.btn20.setText("20")
        self.btn20.setMinimumSize(76, 140)
        self.btn20.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.top_right_layout.addWidget(self.btn20, 1)

        self.btn21 = QtWidgets.QPushButton(parent=self.top_right)
        self.btn21.setText("21")
        self.btn21.setMinimumSize(76, 140)
        self.btn21.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.top_right_layout.addWidget(self.btn21, 1)

        self.btn22 = QtWidgets.QPushButton(parent=self.top_right)
        self.btn22.setText("22")
        self.btn22.setMinimumSize(76, 140)
        self.btn22.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.top_right_layout.addWidget(self.btn22, 1)

        self.btn23 = QtWidgets.QPushButton(parent=self.top_right)
        self.btn23.setText("23")
        self.btn23.setMinimumSize(76, 140)
        self.btn23.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.top_right_layout.addWidget(self.btn23, 1)

        self.btn24 = QtWidgets.QPushButton(parent=self.top_right)
        self.btn24.setText("24")
        self.btn24.setMinimumSize(76, 140)
        self.btn24.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.top_right_layout.addWidget(self.btn24, 1)

        self.btn12 = QtWidgets.QPushButton(parent=self.bottom_left)
        self.btn12.setText("12")
        self.btn12.setMinimumSize(76, 140)
        self.btn12.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.bottom_left_layout.addWidget(self.btn12, 1)

        self.btn11 = QtWidgets.QPushButton(parent=self.bottom_left)
        self.btn11.setText("11")
        self.btn11.setMinimumSize(76, 140)
        self.btn11.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.bottom_left_layout.addWidget(self.btn11, 1)

        self.btn10 = QtWidgets.QPushButton(parent=self.bottom_left)
        self.btn10.setText("10")
        self.btn10.setMinimumSize(76, 140)
        self.btn10.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.bottom_left_layout.addWidget(self.btn10, 1)

        self.btn9 = QtWidgets.QPushButton(parent=self.bottom_left)
        self.btn9.setText("9")
        self.btn9.setMinimumSize(76, 140)
        self.btn9.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.bottom_left_layout.addWidget(self.btn9, 1)

        self.btn8 = QtWidgets.QPushButton(parent=self.bottom_left)
        self.btn8.setText("8")
        self.btn8.setMinimumSize(76, 140)
        self.btn8.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.bottom_left_layout.addWidget(self.btn8, 1)

        self.btn7 = QtWidgets.QPushButton(parent=self.bottom_left)
        self.btn7.setText("7")
        self.btn7.setMinimumSize(76, 140)
        self.btn7.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.bottom_left_layout.addWidget(self.btn7, 1)

        self.btn6 = QtWidgets.QPushButton(parent=self.bottom_right)
        self.btn6.setText("6")
        self.btn6.setMinimumSize(76, 140)
        self.btn6.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.bottom_right_layout.addWidget(self.btn6, 1)

        self.btn5 = QtWidgets.QPushButton(parent=self.bottom_right)
        self.btn5.setText("5")
        self.btn5.setMinimumSize(76, 140)
        self.btn5.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.bottom_right_layout.addWidget(self.btn5, 1)

        self.btn4 = QtWidgets.QPushButton(parent=self.bottom_right)
        self.btn4.setText("4")
        self.btn4.setMinimumSize(76, 140)
        self.btn4.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.bottom_right_layout.addWidget(self.btn4, 1)

        self.btn3 = QtWidgets.QPushButton(parent=self.bottom_right)
        self.btn3.setText("3")
        self.btn3.setMinimumSize(76, 140)
        self.btn3.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.bottom_right_layout.addWidget(self.btn3, 1)

        self.btn2 = QtWidgets.QPushButton(parent=self.bottom_right)
        self.btn2.setText("2")
        self.btn2.setMinimumSize(76, 140)
        self.btn2.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.bottom_right_layout.addWidget(self.btn2, 1)

        self.btn1 = QtWidgets.QPushButton(parent=self.bottom_right)
        self.btn1.setText("1")
        self.btn1.setMinimumSize(76, 140)
        self.btn1.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.bottom_right_layout.addWidget(self.btn1, 1)

        self.bar = QtWidgets.QFrame(parent=self.board_frame)
        self.bar.setFixedWidth(130)
        self.bar.setStyleSheet("background: #ff9933; border: 1px solid black;")
        self.bar_layout = QtWidgets.QVBoxLayout(self.bar)
        self.bar_layout.setContentsMargins(8, 8, 8, 8)
        self.bar_layout.setSpacing(8)

        self.broken_title = QtWidgets.QLabel(parent=self.bar)
        self.broken_title.setText("KIRIK\nTAŞLAR")
        self.broken_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.broken_title.setStyleSheet("font-weight: bold; border: 0;")
        self.bar_layout.addWidget(self.broken_title)

        self.lbl_white_broken = QtWidgets.QLabel(parent=self.bar)
        self.lbl_white_broken.setText("Beyaz Taş: 0")
        self.lbl_white_broken.setStyleSheet("border: 0;")
        self.bar_layout.addWidget(self.lbl_white_broken)
        self.btn_white_return = QtWidgets.QPushButton(parent=self.bar)
        self.btn_white_return.setText("Beyaz Geri Getir")
        self.bar_layout.addWidget(self.btn_white_return)

        self.lbl_brown_broken = QtWidgets.QLabel(parent=self.bar)
        self.lbl_brown_broken.setText("Kahverengi Taş: 0")
        self.lbl_brown_broken.setStyleSheet("border: 0;")
        self.bar_layout.addWidget(self.lbl_brown_broken)
        self.btn_brown_return = QtWidgets.QPushButton(parent=self.bar)
        self.btn_brown_return.setText("Kahverengi Geri Getir")
        self.bar_layout.addWidget(self.btn_brown_return)
        self.bar_layout.addStretch()

        self.middle_left = QtWidgets.QLabel(parent=self.board_frame)
        self.middle_left.setFixedHeight(34)
        self.middle_left.setStyleSheet("background: #ff9933; border: 1px solid black;")
        self.middle_right = QtWidgets.QLabel(parent=self.board_frame)
        self.middle_right.setFixedHeight(34)
        self.middle_right.setStyleSheet("background: #ff9933; border: 1px solid black;")

        self.board_layout.addWidget(self.top_left, 0, 0)
        self.board_layout.addWidget(self.bar, 0, 1, 3, 1)
        self.board_layout.addWidget(self.top_right, 0, 2)
        self.board_layout.addWidget(self.middle_left, 1, 0)
        self.board_layout.addWidget(self.middle_right, 1, 2)
        self.board_layout.addWidget(self.bottom_left, 2, 0)
        self.board_layout.addWidget(self.bottom_right, 2, 2)
        self.board_layout.setColumnStretch(0, 1)
        self.board_layout.setColumnStretch(2, 1)
        self.board_layout.setRowStretch(0, 1)
        self.board_layout.setRowStretch(2, 1)

        self.out_frame = QtWidgets.QFrame(parent=self.board_frame)
        self.out_frame.setStyleSheet("background: #ff9933; border: 1px solid black;")
        self.out_layout = QtWidgets.QHBoxLayout(self.out_frame)
        self.out_layout.setContentsMargins(10, 6, 10, 6)
        self.lbl_white_out = QtWidgets.QLabel(parent=self.out_frame)
        self.lbl_white_out.setText("Beyaz Çıkardı: 0")
        self.lbl_white_out.setStyleSheet("border: 0;")
        self.lbl_brown_out = QtWidgets.QLabel(parent=self.out_frame)
        self.lbl_brown_out.setText("Kahverengi Çıkardı: 0")
        self.lbl_brown_out.setStyleSheet("border: 0;")
        self.out_layout.addWidget(self.lbl_white_out)
        self.out_layout.addWidget(self.lbl_brown_out)
        self.board_layout.addWidget(self.out_frame, 3, 2)

        self.side = QtWidgets.QFrame(parent=TavlaGameWindow)
        self.side.setMinimumWidth(300)
        self.side.setMaximumWidth(360)
        self.side_layout = QtWidgets.QVBoxLayout(self.side)
        self.side_layout.setContentsMargins(0, 0, 0, 0)
        self.side_layout.setSpacing(4)
        self.log_title = QtWidgets.QLabel(parent=self.side)
        self.log_title.setText("Oyun Günlüğü")
        self.log_title.setStyleSheet("font-weight: bold; font-size: 14px;")
        self.side_layout.addWidget(self.log_title)
        self.txt_log = QtWidgets.QPlainTextEdit(parent=self.side)
        self.txt_log.setReadOnly(True)
        self.txt_log.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.side_layout.addWidget(self.txt_log, 1)
        self.bodyLayout.addWidget(self.side)
